// Code generated by protoc-gen-go. DO NOT EDIT.
// source: unixfs.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Data_DataType int32

const (
	Data_Raw       Data_DataType = 0
	Data_Directory Data_DataType = 1
	Data_File      Data_DataType = 2
	Data_Metadata  Data_DataType = 3
	Data_Symlink   Data_DataType = 4
	Data_HAMTShard Data_DataType = 5
)

var Data_DataType_name = map[int32]string{
	0: "Raw",
	1: "Directory",
	2: "File",
	3: "Metadata",
	4: "Symlink",
	5: "HAMTShard",
}
var Data_DataType_value = map[string]int32{
	"Raw":       0,
	"Directory": 1,
	"File":      2,
	"Metadata":  3,
	"Symlink":   4,
	"HAMTShard": 5,
}

func (x Data_DataType) Enum() *Data_DataType {
	p := new(Data_DataType)
	*p = x
	return p
}
func (x Data_DataType) String() string {
	return proto.EnumName(Data_DataType_name, int32(x))
}
func (x *Data_DataType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Data_DataType_value, data, "Data_DataType")
	if err != nil {
		return err
	}
	*x = Data_DataType(value)
	return nil
}
func (Data_DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_unixfs_9241a44c5e644da1, []int{0, 0}
}

type Data struct {
	Type                 *Data_DataType `protobuf:"varint,1,req,name=Type,enum=main.Data_DataType" json:"Type,omitempty"`
	Data                 []byte         `protobuf:"bytes,2,opt,name=Data" json:"Data,omitempty"`
	Filesize             *uint64        `protobuf:"varint,3,opt,name=filesize" json:"filesize,omitempty"`
	Blocksizes           []uint64       `protobuf:"varint,4,rep,name=blocksizes" json:"blocksizes,omitempty"`
	HashType             *uint64        `protobuf:"varint,5,opt,name=hashType" json:"hashType,omitempty"`
	Fanout               *uint64        `protobuf:"varint,6,opt,name=fanout" json:"fanout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_unixfs_9241a44c5e644da1, []int{0}
}
func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (dst *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(dst, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetType() Data_DataType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Data_Raw
}

func (m *Data) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Data) GetFilesize() uint64 {
	if m != nil && m.Filesize != nil {
		return *m.Filesize
	}
	return 0
}

func (m *Data) GetBlocksizes() []uint64 {
	if m != nil {
		return m.Blocksizes
	}
	return nil
}

func (m *Data) GetHashType() uint64 {
	if m != nil && m.HashType != nil {
		return *m.HashType
	}
	return 0
}

func (m *Data) GetFanout() uint64 {
	if m != nil && m.Fanout != nil {
		return *m.Fanout
	}
	return 0
}

type Metadata struct {
	MimeType             *string  `protobuf:"bytes,1,opt,name=MimeType" json:"MimeType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_unixfs_9241a44c5e644da1, []int{1}
}
func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (dst *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(dst, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetMimeType() string {
	if m != nil && m.MimeType != nil {
		return *m.MimeType
	}
	return ""
}

func init() {
	proto.RegisterType((*Data)(nil), "main.Data")
	proto.RegisterType((*Metadata)(nil), "main.Metadata")
	proto.RegisterEnum("main.Data_DataType", Data_DataType_name, Data_DataType_value)
}

func init() { proto.RegisterFile("unixfs.proto", fileDescriptor_unixfs_9241a44c5e644da1) }

var fileDescriptor_unixfs_9241a44c5e644da1 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0x80, 0x71, 0xe2, 0xb6, 0xe9, 0x11, 0x2a, 0xeb, 0x58, 0x3c, 0x30, 0x84, 0x4c, 0x9e, 0x32,
	0xf0, 0x06, 0x48, 0x15, 0x62, 0xc9, 0x42, 0x2b, 0xf6, 0xa3, 0x75, 0x14, 0xab, 0x49, 0x5c, 0xc5,
	0xae, 0x20, 0xbc, 0x28, 0xaf, 0x83, 0x2e, 0x20, 0x58, 0x4e, 0xba, 0xfb, 0xbe, 0xfb, 0x83, 0xfc,
	0x32, 0xb8, 0x8f, 0x26, 0x54, 0xe7, 0xd1, 0x47, 0x8f, 0xb2, 0x27, 0x37, 0x94, 0x5f, 0x02, 0xe4,
	0x96, 0x22, 0xe1, 0x3d, 0xc8, 0xfd, 0x74, 0xb6, 0x5a, 0x14, 0x89, 0xd9, 0x3c, 0xdc, 0x56, 0x4c,
	0x2b, 0x26, 0x73, 0x60, 0x84, 0xf9, 0x8f, 0xaa, 0x93, 0x42, 0x98, 0x1c, 0x15, 0x64, 0x8d, 0xeb,
	0x6c, 0x70, 0x9f, 0x56, 0xa7, 0x85, 0x30, 0x12, 0x11, 0xe0, 0xad, 0xf3, 0x87, 0x13, 0x97, 0x82,
	0x96, 0x45, 0x6a, 0x24, 0x5b, 0x2d, 0x85, 0x76, 0x1e, 0xbd, 0x98, 0xad, 0x0d, 0x2c, 0x1b, 0x1a,
	0xfc, 0x25, 0xea, 0x25, 0xe7, 0xe5, 0x2b, 0x64, 0x7f, 0x1b, 0x56, 0x90, 0xbe, 0xd0, 0xbb, 0xba,
	0xc2, 0x1b, 0x58, 0x6f, 0xdd, 0x68, 0x0f, 0xd1, 0x8f, 0x93, 0x12, 0x98, 0x81, 0x7c, 0x72, 0x9d,
	0x55, 0x09, 0xe6, 0x90, 0xd5, 0x36, 0xd2, 0x91, 0x22, 0xa9, 0x14, 0xaf, 0x61, 0xb5, 0x9b, 0xfa,
	0xce, 0x0d, 0x27, 0x25, 0xb9, 0xe7, 0xf9, 0xb1, 0xde, 0xef, 0x5a, 0x1a, 0x8f, 0x6a, 0x51, 0xde,
	0xfd, 0x9b, 0x7c, 0x45, 0xed, 0x7a, 0xfb, 0xfb, 0xa0, 0x30, 0xeb, 0xef, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xaf, 0x0d, 0xee, 0xe9, 0x0c, 0x01, 0x00, 0x00,
}
